version: "3"

services:
  php:
    container_name: php
    tty: true
    volumes: 
      - ./:/www/
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
