version: "3"

services:
  brasil_tecpar:
    container_name: brasil_tecpar
    tty: true
    volumes: 
      - ./:/www/
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
